### ISSUE TITLE
Error running CopyKeysSinglePass-Az.ps1

### ISSUE THREAD

**Issue by rmunilla** [AsrOneSdk/published-scripts#10]
Hi,

while trying to run CopyKeysSinglePass-Az.ps1 we get this error:

`Unhandled Exception: System.TypeLoadException: Could not load type 'System.Runtime.InteropServices.StandardOleMarshalObject' from assembly 'System, Version=4.0.0.0,
Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at System.Windows.Forms.Label.OnTextChanged(EventArgs e)
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.Label.set_Text(String value)
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Application.OnThreadException(Exception t)
   at System.Windows.Forms.Control.WndProcException(Exception e)
   at System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

We have .Net Core SDK 3.1, .Net Framework 4.8 SDK and Powershell 6.2.3, can you check what is the problem please?

Thank you

**Comment by punit1396** [comment]
Powershell 6.2.3 (powershell core) uses .net core and that does support the GUI namespaces used (system.windows.forms).
Could you try running the script on the other powershell (5.1)?
